// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

type Activity struct {
	ID         int64
	Name       string
	TimeSlotID int64
}

type TimeSlot struct {
	ID   int64
	Name string
	Time string
}

type UpVote struct {
	ID         int64
	ActivityID int64
	User       string
}
