// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package senatus

type Activity struct {
	ID         int64
	Name       string
	TimeSlotID int64
}

type TimeSlot struct {
	ID   int64
	Time string
}

type Vote struct {
	ID         int64
	ActivityID int64
	User       string
	IsUpvote   bool
}
