// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteTimeSlot = `-- name: DeleteTimeSlot :exec
DELETE FROM time_slots
WHERE id = ?
`

func (q *Queries) DeleteTimeSlot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTimeSlot, id)
	return err
}

const getAllTimeSlots = `-- name: GetAllTimeSlots :many
SELECT ts.id AS time_slot_id,
    ts.time AS time_slot_time,
    a.id AS activity_id,
    a.name AS activity_name,
    v.user AS vote_user,
    v.is_up_vote AS vote_is_up_vote
FROM time_slots ts
    LEFT JOIN activities a ON ts.id = a.time_slot_id
    LEFT JOIN votes v ON a.id = v.activity_id
ORDER BY ts.time
`

type GetAllTimeSlotsRow struct {
	TimeSlotID   int64
	TimeSlotTime string
	ActivityID   sql.NullInt64
	ActivityName sql.NullString
	VoteUser     sql.NullString
	VoteIsUpVote sql.NullInt64
}

func (q *Queries) GetAllTimeSlots(ctx context.Context) ([]GetAllTimeSlotsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTimeSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTimeSlotsRow
	for rows.Next() {
		var i GetAllTimeSlotsRow
		if err := rows.Scan(
			&i.TimeSlotID,
			&i.TimeSlotTime,
			&i.ActivityID,
			&i.ActivityName,
			&i.VoteUser,
			&i.VoteIsUpVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activities (name, time_slot_id)
VALUES (?, ?)
`

type InsertActivityParams struct {
	Name       string
	TimeSlotID int64
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity, arg.Name, arg.TimeSlotID)
	return err
}

const insertTimeSlot = `-- name: InsertTimeSlot :exec
INSERT INTO time_slots (time)
VALUES (?)
`

func (q *Queries) InsertTimeSlot(ctx context.Context, time string) error {
	_, err := q.db.ExecContext(ctx, insertTimeSlot, time)
	return err
}

const vote = `-- name: Vote :exec
INSERT INTO votes (activity_id, user, is_up_vote)
VALUES (?, ?, ?)
`

type VoteParams struct {
	ActivityID int64
	User       string
	IsUpVote   int64
}

func (q *Queries) Vote(ctx context.Context, arg VoteParams) error {
	_, err := q.db.ExecContext(ctx, vote, arg.ActivityID, arg.User, arg.IsUpVote)
	return err
}
